name: DEV - Build

on:
  workflow_dispatch:
  
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

env:
  APP_NAME: thiwaporn-tutorial-frontend
  CONTAINER_REPOSITORY: "acrthiwaporntutorial001.azurecr.io"
  IMAGE_TAG: "0.0.1-SNAPSHOT"